### ISSUE TITLE
Avoid `java.lang.NoClassDefFoundError: scalariform/formatter/preferences/SpacesAroundMultiImports`

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/scala-exercises#293]
As @jackcviers pointed out in the Gitter channel, when downloading and trying to build the project a `java.lang.NoClassDefFoundError: scalariform/formatter/preferences/SpacesAroundMultiImports` error is thrown. This can be worked around adding the following incantation to the sbt plugin configuration:

```scala
dependencyOverrides in ThisBuild += "org.scalariform" %% "scalariform" % "0.1.8"
```

Doesn't this override the Scalariform dependency for every project? This solution is a workaround and we should properly fix this issue, not requiring everyone to fiddle with their sbt configuration. Downloading and building the project should just work.

**Comment by jackcviers** [comment]
> dependencyOverrides in ThisBuild += "org.scalariform" %% "scalariform" % "0.1.8"

I put this in `/core/project/plugins.sbt` and `/site/project/plugins.sbt` and it resulted in the same error. What am I missing @dialelo?

**Comment by dialelo** [comment]
I think you have to put it directly in your SBT configuration, I have it in `~/.sbt/0.13/plugins/plugins.sbt`. I think the project that's causing the conflict is `compiler` but I'm not quite sure, new to sbt/scala myself. /cc @andyscott

**Comment by andyscott** [comment]
If you change your global plugins, I've also found it useful to clear out any cached files from SBT's global installation.

    cd ~/.sbt; \
        rm -r boot/; \
        find **/target -maxdepth 0 | xargs rm -r; \
        find **/staging | xargs rm -rf;

**Comment by jackcviers** [comment]
Gotcha.

**Comment by jackcviers** [comment]
Workaround
=========

As @andyscott and @dialelo  suggested, the issue seems to stem from having [ensime-sbt-cmd](https://github.com/ensime/ensime-sbt) in the global `~/.sbt/0.13/plugins.sbt`. Here's the full workaround I did to have my exercises and ensime too:

In `~/.sbt/0.13/plugins.sbt`, if the following line exists, comment it out:

```scala
addSbtPlugin("org.ensime" % "ensime-sbt" % "0.4.0")
```

and add the [fix](https://github.com/47deg/scala-exercises/issues/293#issue-139826258) from @dialelo above:

```scala
dependencyOverrides in ThisBuild += "org.scalariform" %% "scalariform" % "0.1.8"
```

and save the file.

Then, in `scala-exercises/core/project/plugins.sbt`, add the ensime-sbt-cmd plugin as follows:

```scala
addSbtPlugin("org.ensime" % "ensime-sbt" % "0.4.0")
```

Next, in `scala-exercises/site/project/plugins.sbt`, add the ensime-sbt-cmd plugin as follows:

```scala
addSbtPlugin("org.ensime" % "ensime-sbt" % "0.4.0")
```

Finally, in `scala-exercises/core/build.sbt`, add the following import:

```scala
import org.ensime.Imports.EnsimeKeys.unmanagedSourceArchives
```

and, finally, in `scala-exercises/core/build.sbt`, add the ensime `unmanagedSourceArchives` setting to the `commonSettings` `val`:

```scala
...
 lazy val commonSettings = Seq(
  libraryDependencies ++= testlibs(Dep.scalatest),
  unmanagedSourceArchives := Seq()
 )
...
```

Now open a shell in the `scala-exercises/site/` directory. Run:

```bash
sbt gen-ensime
```

The project will load, and update, bringing in the ensime-sbt-cmd plugin, and will generate a `.ensime` file which you can use to run `ensime` on the project.

Don't forget to take these changes out when you commit back to the project! It's not nice to leave editor/ide/build-diagnostic plugins in a shared project `plugins.sbt` file. I made these changes and stowed them in a git stash so that they wouldn't interfere with others when I commit.

A similar workaround will probably work for other ide plugins/global plugins. You may have to clear out your global sbt dependencies/blow away your local `.ivy2` cache as well. I didn't but YMMV.
