### ISSUE TITLE
Scala Exercises based off of MOOC curriculum

### ISSUE THREAD

**Issue by heathermiller** [scala-exercises/scala-exercises#603]
Hi guys,

I'm not sure if this is the right place to be posting this as this is a content-related point rather than a technical one. So feel free to close/move it if it should be somewhere else.

But in continuing to work on the Scala MOOCs, I just realized that I would love to point people to scala-exercises.com from the MOOC videos and resource pages. In particular for the Spark course, because we expect that people will skip over the previous 3 MOOCs introducing Scala + the fundamentals, just being in a rush to learn Spark.

So I started looking around for something interactive that I could point people at. I immediately thought of scala-exercises, but realized that the stdlib exercises is maybe not the best place to point these people. Not that there's anything wrong with it, it's just maybe not the best beginner-first place to send people trying to get a quick idea of what Scala is all about. 

That said, I was thinking it would be cool if there was a set of exercises based on the first 2 MOOCs (Functional Programming Principles in Scala and Functional Program Design in Scala). The progression that Martin has designed for these courses is really spot on, if you ask me (of course I'm biased). 

Just brainstorming here. Would something like this ever be feasible? (Again, just trying to figure out what I should point fast-track students at)

**Comment by nickelsberry** [comment]
Excellent idea Heather, and very much feasible! We would love to help facilitate this and can dedicate some resources to moving it quickly.

**Comment by heathermiller** [comment]
Awesome! Let me see if I can get someone from the SC side of things to spend some time on this as well. It's always better to work together on stuff like this. Julien might be up for it; I just have to check on his availability. Just for the sake of synchronization the two orgs, who can I direct Julien at if indeed he is available soon? (I'm guessing he'd be free late this week or early next, but again, I have to check with him first to be sure)

**Comment by nickelsberry** [comment]
You can coordinate with @jdesiloniz and if you need anything else just let me know!

**Comment by heathermiller** [comment]
Great. @julienrf said he'd be up to participate :)

**Comment by jdesiloniz** [comment]
Sounds awesome! I'll start creating a new repo/content library for this project, and set up everything so @julienrf and I can work on this. @heathermiller, should I access the content of both MOOCs through Coursera?

**Comment by heathermiller** [comment]
Hey @jdesiloniz, yep! Everything we have (slides, etc) are in those course pages. @julienrf is something of an expert now a days on that course material, so I'm sure he would be interested in working out a structure and maybe has some ideas for examples/exercises (he's something of a wizard when it comes to coming up with stuff like this!)

**Comment by jdesiloniz** [comment]
Hey @heathermiller. Sorry for the delay. I just added two new repos to the scala-exercises organization, one for each one of the courses you mentioned:

* https://github.com/scala-exercises/exercises-fpprinciples
* https://github.com/scala-exercises/exercises-fpdesign

So far, they only have an initial (but working) structure so that we can start inserting content right away. I guess @julienrf and me can coordinate through both repos issues, but I don't know if he's got an idea on the structure of contents and other details. It'd be nice to hear from him about it.

About the "FP design in Scala" course, so far I haven't been able to access the content (it's starting in Coursera in November), but I've already access the "FP principles in Scala" so I have the material available to work on that library.

**Comment by julienrf** [comment]
Hi @jdesiloniz! Thanks for the work you achieved on this topic. I’d like to get some more time to think about the structure of the contents, can I ping you in a few days? In the meanwhile, feel free tell me if you have any specific idea in mind!
Also, I will give you access to the MOOCs so that you don’t have to wait for them to start.

**Comment by jdesiloniz** [comment]
@julienrf sure! I'll be looking forward to that. Thanks!

**Comment by julienrf** [comment]
Hi,

I started putting a syllabus [here](https://workflowy.com/s/Y87jf6RPht). It is not really exactly following the MOOCs, here are the main differences:
- early introduction of algebraic data types (even before classes) ;
- no FRP.

Also, it has some overlaps with the “std_lib” course. I don’t really know how to manage that.

What do you all think of the level of details?

**Comment by jdesiloniz** [comment]
Hi Julien, great job! I think it's greatly detailed!

This would cover the contents of the first MOOC, right? (i.e.: it doesn't cover Monads, for-comprehensions...). The only thing it kind of got me was the mention of imperative programming, vars, while loops, etc. I don't know if the idea there is to show how not having referential transparency can lead to trouble.

The only thing I would mention (and it doesn't really has nothing to do with the syllabus here) is that Scala Exercises has some limitations regarding the kind of exercises you can create. That is: right now you can only create "fill-the-gaps"-kind of exercises (i.e.: we don't have features to let users implement whole classes, or use functions or other named structures in the exercise scope ~yet~). So we should take that into account when thinking about the structure of the exercises.

**Comment by julienrf** [comment]
> This would cover the contents of the first MOOC, right?This would cover the contents of the first MOOC, right?

I indeed omitted to detail monads as they are in progfun2, but there is a section on for expressions. And, beside FRP and monads, everything that’s in progfun2 is covered (lazy evaluation, streams, identity and state).

> The only thing it kind of got me was the mention of imperative programming, vars, while loops, etc. I don't know if the idea there is to show how not having referential transparency can lead to trouble.

I think it is worth presenting vars and imperative programming, because they are useful in some situations despite they lead to referential transparency loss. Does that make sense to you?

**Comment by jdesiloniz** [comment]
Oh great, I was thinking that was a lot of points to cover for only one MOOC. Now that makes sense! Does it make sense for you to have all this content in one single library? Or have it split on two? 

About your thoughts on imperative programming, I see your point. As long as a beginner user can recognize the eventual problems the use of mutation can bring in the library contents, I'm OK with it!

**Comment by julienrf** [comment]
I think it would be better to have it as a single library.

**Comment by jdesiloniz** [comment]
👍

**Comment by heathermiller** [comment]
@julienrf I think this is perfect! I couldn't have designed things better. :) Looks great to me!
