### ISSUE TITLE
Break up results of compound exercises

### ISSUE THREAD

**Issue by nestorpersist** [scala-exercises/scala-exercises#611]
Looking at Cats, each exercise has multiple steps/answers. When I run if any are wrong all are marked in red. Would it not make sense to mark only the wrong ones in red?

I find the user experience to be poor. Suppose there are 4 parts and I get 3 right and one wrong. Since the all show red, I am confused about which was the one I got wrong. 

So either break up the exercises so that each can be run separately or run them together but mark in green those parts that are correct.

**Comment by rafaparadela** [comment]
Thanks @nestorpersist . I agree that having several assertions in the same exercise decrease the user experience. This could be fixed very easily just splitting them. 
On the other hand we will try to provide more feedback if the evaluation fails, in order to infer which assertion has not been fulfilled.

**Comment by rafaparadela** [comment]
I will close this issue since we will tackle it under the context of #572
